version: "3"
services:
 
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - data-streaming-with-apache-kafka-spark-andmongodb_default

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'          #change to 9093 to access external from your windows host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT     #add aditional listener for external
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093                              #9092 will be for other containers, 9093 for your windows client
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093     #9092 will be for other containers, 9093 for your windows client
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  # kafka_manager:
  #   image: hlebalbau/kafka-manager:stable
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   environment:
  #     ZK_HOSTS: "zookeeper:2181"
  #     APPLICATION_SECRET: "random-secret"
  #   command: -Dpidfile.path=/dev/null

    
    networks:
      - data-streaming-with-apache-kafka-spark-andmongodb_default

  spark:
    image: 'jupyter/pyspark-notebook:spark-2'
    ports:
      - '8888:8888'
      - "4040-4080:4040-4080"
    volumes:
      - ./ApacheSpark/:/home/jovyan/work
    networks:
      - data-streaming-with-apache-kafka-spark-andmongodb_default

  api-ingest:
    image: 'api-ingest'
    ports:
       - '8080:80'
    networks:
      - data-streaming-with-apache-kafka-spark-andmongodb_default

networks:
  data-streaming-with-apache-kafka-spark-andmongodb_default:
    driver: bridge
  
# docker-compose -f docker-compose-kafka-spark.yml up